version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: password_manager
    ports:
      - "3306:3306"

  password-manager-app:
    build: .
    container_name: password-manager-app
    depends_on:
      - mysql
    ports:
      - "5000:5000"
