version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: password_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"

  password-app:
    build: .
    container_name: password-manager-app
    depends_on:
      - mysql
    environment:
      PYTHONUNBUFFERED: 1
    stdin_open: true
    tty: true
