apiVersion: v1
kind: Service
metadata:
  name: password-manager
spec:
  selector:
    app: password-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-manager
  template:
    metadata:
      labels:
        app: password-manager
    spec:
      containers:
        - name: app
          image: your-dockerhub-username/password-manager:latest
          ports:
            - containerPort: 8000
