apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3M=      # rootpass
  mysql-user: dXNlcg==                  # user
  mysql-password: dXNlcnBhc3M=          # userpass
